version: "1"

services:
  rabbit:
    container_name: benchmaker-rabbitmq
    image: rabbitmq:3.6-management
    ports:
      - "15673:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always

  bottleneck:
    container_name: bottleneck
    image: chunchill/benchmarker-bottleneck
    ports:
      - "8001:8000"
    links:
      - "rabbit:benchmarker-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
  qtip:
    container_name: benchmarker-qtip
    image: chunchill/benchmarker-qtip
    ports:
      - "8002:8000"
    links:
      - "rabbit:benchmarker-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  storperf:
    container_name: benchmarker-storperf
    image: chunchill/benchmarker-storperf
    ports:
      - "8003:8000"
  vsperf:
    container_name: benchmarker-vsperf
    image: chunchill/benchmarker-vsperf
    ports:
      - "8004:8000"
    links:
      - "rabbit:benchmarker-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  yardstick-availability:
    container_name: benchmarker-availability
    image: chunchill/benchmarker-availability
    ports:
      - "8005:8000"
    links:
      - "rabbit:benchmarker-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  yardstick-compute:
    container_name: benchmarker-compute
    image: chunchill/benchmarker-compute
    ports:
      - "8006:8000"
    links:
      - "rabbit:benchmarker-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  yardstick-feature:
    container_name: benchmarker-feature
    image: chunchill/benchmarker-feature
    ports:
      - "8007:8000"
    links:
      - "rabbit:benchmarker-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  yardstick-networking:
    container_name: benchmarker-networking
    image: chunchill/benchmarker-networking
    ports:
      - "8008:8000"
    links:
      - "rabbit:benchmarker-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  yardstick-storage:
    container_name: benchmarker-storage
    image: chunchill/benchmarker-storage
    ports:
      - "8009:8000"
    links:
      - "rabbit:benchmarker-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

  gateway:
    container_name: benchmarker-gateway
    image: chunchill/benchmarker-gateway
    ports:
      - "8010:8000"
    links:
      - "rabbit:benchmarker-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"

